### PR TITLE
Css ecommerce page

### PR DESCRIPTION
**Pull request by AnthonyVNgo**
Screen Shot 2022-03-22 at 22 34 29

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Anthony! You are missing a border-radius on the current price's background color, and your images are slightly too far apart as compared to the example. Please revise and submit a new screenshot with your revision.

**Comment by AnthonyVNgo** [comment]
Screen Shot 2022-03-23 at 23 03 00

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude! All of your `p` elements are missing closing tags 🤢

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
